/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppTherapistsRouteImport } from './routes/_app.therapists'
import { Route as AppServicesRouteImport } from './routes/_app.services'
import { Route as AppProgressRouteImport } from './routes/_app.progress'
import { Route as AppProgrammesRouteImport } from './routes/_app.programmes'
import { Route as AppPatientsRouteImport } from './routes/_app.patients'
import { Route as AppMessagesRouteImport } from './routes/_app.messages'
import { Route as AppLocationsRouteImport } from './routes/_app.locations'
import { Route as AppHomeVisitsRouteImport } from './routes/_app.home-visits'
import { Route as AppEmrRouteImport } from './routes/_app.emr'
import { Route as AppDocumentsRouteImport } from './routes/_app.documents'
import { Route as AppBillingRouteImport } from './routes/_app.billing'
import { Route as AppAppointmentsRouteImport } from './routes/_app.appointments'
import { Route as AppAiRouteImport } from './routes/_app.ai'
import { Route as AppEmrIndexRouteImport } from './routes/_app.emr.index'
import { Route as AppAiIndexRouteImport } from './routes/_app.ai.index'
import { Route as AppTherapistsIdRouteImport } from './routes/_app.therapists.$id'
import { Route as AppPatientsIdRouteImport } from './routes/_app.patients.$id'
import { Route as AppEmrTemplatesRouteImport } from './routes/_app.emr.templates'
import { Route as AppEmrRecordsRouteImport } from './routes/_app.emr.records'
import { Route as AppEmrIdRouteImport } from './routes/_app.emr.$id'
import { Route as AppAppointmentsNewRouteImport } from './routes/_app.appointments.new'
import { Route as AppAppointmentsIdRouteImport } from './routes/_app.appointments.$id'
import { Route as AppAiLogsRouteImport } from './routes/_app.ai.logs'
import { Route as AppAiKnowledgeRouteImport } from './routes/_app.ai.knowledge'
import { Route as AppAiConfigRouteImport } from './routes/_app.ai.config'
import { Route as AppEmrConsentIndexRouteImport } from './routes/_app.emr.consent.index'
import { Route as AppEmrConsentIdRouteImport } from './routes/_app.emr.consent.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTherapistsRoute = AppTherapistsRouteImport.update({
  id: '/therapists',
  path: '/therapists',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesRoute = AppServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRoute,
} as any)
const AppProgrammesRoute = AppProgrammesRouteImport.update({
  id: '/programmes',
  path: '/programmes',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsRoute = AppPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppLocationsRoute = AppLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeVisitsRoute = AppHomeVisitsRouteImport.update({
  id: '/home-visits',
  path: '/home-visits',
  getParentRoute: () => AppRoute,
} as any)
const AppEmrRoute = AppEmrRouteImport.update({
  id: '/emr',
  path: '/emr',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppAppointmentsRoute = AppAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppEmrIndexRoute = AppEmrIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppEmrRoute,
} as any)
const AppAiIndexRoute = AppAiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAiRoute,
} as any)
const AppTherapistsIdRoute = AppTherapistsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppTherapistsRoute,
} as any)
const AppPatientsIdRoute = AppPatientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPatientsRoute,
} as any)
const AppEmrTemplatesRoute = AppEmrTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppEmrRoute,
} as any)
const AppEmrRecordsRoute = AppEmrRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => AppEmrRoute,
} as any)
const AppEmrIdRoute = AppEmrIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppEmrRoute,
} as any)
const AppAppointmentsNewRoute = AppAppointmentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppAppointmentsRoute,
} as any)
const AppAppointmentsIdRoute = AppAppointmentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAppointmentsRoute,
} as any)
const AppAiLogsRoute = AppAiLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppAiRoute,
} as any)
const AppAiKnowledgeRoute = AppAiKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppAiRoute,
} as any)
const AppAiConfigRoute = AppAiConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AppAiRoute,
} as any)
const AppEmrConsentIndexRoute = AppEmrConsentIndexRouteImport.update({
  id: '/consent/',
  path: '/consent/',
  getParentRoute: () => AppEmrRoute,
} as any)
const AppEmrConsentIdRoute = AppEmrConsentIdRouteImport.update({
  id: '/consent/$id',
  path: '/consent/$id',
  getParentRoute: () => AppEmrRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/ai': typeof AppAiRouteWithChildren
  '/appointments': typeof AppAppointmentsRouteWithChildren
  '/billing': typeof AppBillingRoute
  '/documents': typeof AppDocumentsRoute
  '/emr': typeof AppEmrRouteWithChildren
  '/home-visits': typeof AppHomeVisitsRoute
  '/locations': typeof AppLocationsRoute
  '/messages': typeof AppMessagesRoute
  '/patients': typeof AppPatientsRouteWithChildren
  '/programmes': typeof AppProgrammesRoute
  '/progress': typeof AppProgressRoute
  '/services': typeof AppServicesRoute
  '/therapists': typeof AppTherapistsRouteWithChildren
  '/ai/config': typeof AppAiConfigRoute
  '/ai/knowledge': typeof AppAiKnowledgeRoute
  '/ai/logs': typeof AppAiLogsRoute
  '/appointments/$id': typeof AppAppointmentsIdRoute
  '/appointments/new': typeof AppAppointmentsNewRoute
  '/emr/$id': typeof AppEmrIdRoute
  '/emr/records': typeof AppEmrRecordsRoute
  '/emr/templates': typeof AppEmrTemplatesRoute
  '/patients/$id': typeof AppPatientsIdRoute
  '/therapists/$id': typeof AppTherapistsIdRoute
  '/ai/': typeof AppAiIndexRoute
  '/emr/': typeof AppEmrIndexRoute
  '/emr/consent/$id': typeof AppEmrConsentIdRoute
  '/emr/consent/': typeof AppEmrConsentIndexRoute
}
export interface FileRoutesByTo {
  '/appointments': typeof AppAppointmentsRouteWithChildren
  '/billing': typeof AppBillingRoute
  '/documents': typeof AppDocumentsRoute
  '/home-visits': typeof AppHomeVisitsRoute
  '/locations': typeof AppLocationsRoute
  '/messages': typeof AppMessagesRoute
  '/patients': typeof AppPatientsRouteWithChildren
  '/programmes': typeof AppProgrammesRoute
  '/progress': typeof AppProgressRoute
  '/services': typeof AppServicesRoute
  '/therapists': typeof AppTherapistsRouteWithChildren
  '/': typeof AppIndexRoute
  '/ai/config': typeof AppAiConfigRoute
  '/ai/knowledge': typeof AppAiKnowledgeRoute
  '/ai/logs': typeof AppAiLogsRoute
  '/appointments/$id': typeof AppAppointmentsIdRoute
  '/appointments/new': typeof AppAppointmentsNewRoute
  '/emr/$id': typeof AppEmrIdRoute
  '/emr/records': typeof AppEmrRecordsRoute
  '/emr/templates': typeof AppEmrTemplatesRoute
  '/patients/$id': typeof AppPatientsIdRoute
  '/therapists/$id': typeof AppTherapistsIdRoute
  '/ai': typeof AppAiIndexRoute
  '/emr': typeof AppEmrIndexRoute
  '/emr/consent/$id': typeof AppEmrConsentIdRoute
  '/emr/consent': typeof AppEmrConsentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/ai': typeof AppAiRouteWithChildren
  '/_app/appointments': typeof AppAppointmentsRouteWithChildren
  '/_app/billing': typeof AppBillingRoute
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/emr': typeof AppEmrRouteWithChildren
  '/_app/home-visits': typeof AppHomeVisitsRoute
  '/_app/locations': typeof AppLocationsRoute
  '/_app/messages': typeof AppMessagesRoute
  '/_app/patients': typeof AppPatientsRouteWithChildren
  '/_app/programmes': typeof AppProgrammesRoute
  '/_app/progress': typeof AppProgressRoute
  '/_app/services': typeof AppServicesRoute
  '/_app/therapists': typeof AppTherapistsRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/ai/config': typeof AppAiConfigRoute
  '/_app/ai/knowledge': typeof AppAiKnowledgeRoute
  '/_app/ai/logs': typeof AppAiLogsRoute
  '/_app/appointments/$id': typeof AppAppointmentsIdRoute
  '/_app/appointments/new': typeof AppAppointmentsNewRoute
  '/_app/emr/$id': typeof AppEmrIdRoute
  '/_app/emr/records': typeof AppEmrRecordsRoute
  '/_app/emr/templates': typeof AppEmrTemplatesRoute
  '/_app/patients/$id': typeof AppPatientsIdRoute
  '/_app/therapists/$id': typeof AppTherapistsIdRoute
  '/_app/ai/': typeof AppAiIndexRoute
  '/_app/emr/': typeof AppEmrIndexRoute
  '/_app/emr/consent/$id': typeof AppEmrConsentIdRoute
  '/_app/emr/consent/': typeof AppEmrConsentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/appointments'
    | '/billing'
    | '/documents'
    | '/emr'
    | '/home-visits'
    | '/locations'
    | '/messages'
    | '/patients'
    | '/programmes'
    | '/progress'
    | '/services'
    | '/therapists'
    | '/ai/config'
    | '/ai/knowledge'
    | '/ai/logs'
    | '/appointments/$id'
    | '/appointments/new'
    | '/emr/$id'
    | '/emr/records'
    | '/emr/templates'
    | '/patients/$id'
    | '/therapists/$id'
    | '/ai/'
    | '/emr/'
    | '/emr/consent/$id'
    | '/emr/consent/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/appointments'
    | '/billing'
    | '/documents'
    | '/home-visits'
    | '/locations'
    | '/messages'
    | '/patients'
    | '/programmes'
    | '/progress'
    | '/services'
    | '/therapists'
    | '/'
    | '/ai/config'
    | '/ai/knowledge'
    | '/ai/logs'
    | '/appointments/$id'
    | '/appointments/new'
    | '/emr/$id'
    | '/emr/records'
    | '/emr/templates'
    | '/patients/$id'
    | '/therapists/$id'
    | '/ai'
    | '/emr'
    | '/emr/consent/$id'
    | '/emr/consent'
  id:
    | '__root__'
    | '/_app'
    | '/_app/ai'
    | '/_app/appointments'
    | '/_app/billing'
    | '/_app/documents'
    | '/_app/emr'
    | '/_app/home-visits'
    | '/_app/locations'
    | '/_app/messages'
    | '/_app/patients'
    | '/_app/programmes'
    | '/_app/progress'
    | '/_app/services'
    | '/_app/therapists'
    | '/_app/'
    | '/_app/ai/config'
    | '/_app/ai/knowledge'
    | '/_app/ai/logs'
    | '/_app/appointments/$id'
    | '/_app/appointments/new'
    | '/_app/emr/$id'
    | '/_app/emr/records'
    | '/_app/emr/templates'
    | '/_app/patients/$id'
    | '/_app/therapists/$id'
    | '/_app/ai/'
    | '/_app/emr/'
    | '/_app/emr/consent/$id'
    | '/_app/emr/consent/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/therapists': {
      id: '/_app/therapists'
      path: '/therapists'
      fullPath: '/therapists'
      preLoaderRoute: typeof AppTherapistsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services': {
      id: '/_app/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AppServicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/progress': {
      id: '/_app/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/programmes': {
      id: '/_app/programmes'
      path: '/programmes'
      fullPath: '/programmes'
      preLoaderRoute: typeof AppProgrammesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patients': {
      id: '/_app/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AppPatientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages': {
      id: '/_app/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/locations': {
      id: '/_app/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof AppLocationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home-visits': {
      id: '/_app/home-visits'
      path: '/home-visits'
      fullPath: '/home-visits'
      preLoaderRoute: typeof AppHomeVisitsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/emr': {
      id: '/_app/emr'
      path: '/emr'
      fullPath: '/emr'
      preLoaderRoute: typeof AppEmrRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/appointments': {
      id: '/_app/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppAppointmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai': {
      id: '/_app/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/emr/': {
      id: '/_app/emr/'
      path: '/'
      fullPath: '/emr/'
      preLoaderRoute: typeof AppEmrIndexRouteImport
      parentRoute: typeof AppEmrRoute
    }
    '/_app/ai/': {
      id: '/_app/ai/'
      path: '/'
      fullPath: '/ai/'
      preLoaderRoute: typeof AppAiIndexRouteImport
      parentRoute: typeof AppAiRoute
    }
    '/_app/therapists/$id': {
      id: '/_app/therapists/$id'
      path: '/$id'
      fullPath: '/therapists/$id'
      preLoaderRoute: typeof AppTherapistsIdRouteImport
      parentRoute: typeof AppTherapistsRoute
    }
    '/_app/patients/$id': {
      id: '/_app/patients/$id'
      path: '/$id'
      fullPath: '/patients/$id'
      preLoaderRoute: typeof AppPatientsIdRouteImport
      parentRoute: typeof AppPatientsRoute
    }
    '/_app/emr/templates': {
      id: '/_app/emr/templates'
      path: '/templates'
      fullPath: '/emr/templates'
      preLoaderRoute: typeof AppEmrTemplatesRouteImport
      parentRoute: typeof AppEmrRoute
    }
    '/_app/emr/records': {
      id: '/_app/emr/records'
      path: '/records'
      fullPath: '/emr/records'
      preLoaderRoute: typeof AppEmrRecordsRouteImport
      parentRoute: typeof AppEmrRoute
    }
    '/_app/emr/$id': {
      id: '/_app/emr/$id'
      path: '/$id'
      fullPath: '/emr/$id'
      preLoaderRoute: typeof AppEmrIdRouteImport
      parentRoute: typeof AppEmrRoute
    }
    '/_app/appointments/new': {
      id: '/_app/appointments/new'
      path: '/new'
      fullPath: '/appointments/new'
      preLoaderRoute: typeof AppAppointmentsNewRouteImport
      parentRoute: typeof AppAppointmentsRoute
    }
    '/_app/appointments/$id': {
      id: '/_app/appointments/$id'
      path: '/$id'
      fullPath: '/appointments/$id'
      preLoaderRoute: typeof AppAppointmentsIdRouteImport
      parentRoute: typeof AppAppointmentsRoute
    }
    '/_app/ai/logs': {
      id: '/_app/ai/logs'
      path: '/logs'
      fullPath: '/ai/logs'
      preLoaderRoute: typeof AppAiLogsRouteImport
      parentRoute: typeof AppAiRoute
    }
    '/_app/ai/knowledge': {
      id: '/_app/ai/knowledge'
      path: '/knowledge'
      fullPath: '/ai/knowledge'
      preLoaderRoute: typeof AppAiKnowledgeRouteImport
      parentRoute: typeof AppAiRoute
    }
    '/_app/ai/config': {
      id: '/_app/ai/config'
      path: '/config'
      fullPath: '/ai/config'
      preLoaderRoute: typeof AppAiConfigRouteImport
      parentRoute: typeof AppAiRoute
    }
    '/_app/emr/consent/': {
      id: '/_app/emr/consent/'
      path: '/consent'
      fullPath: '/emr/consent/'
      preLoaderRoute: typeof AppEmrConsentIndexRouteImport
      parentRoute: typeof AppEmrRoute
    }
    '/_app/emr/consent/$id': {
      id: '/_app/emr/consent/$id'
      path: '/consent/$id'
      fullPath: '/emr/consent/$id'
      preLoaderRoute: typeof AppEmrConsentIdRouteImport
      parentRoute: typeof AppEmrRoute
    }
  }
}

interface AppAiRouteChildren {
  AppAiConfigRoute: typeof AppAiConfigRoute
  AppAiKnowledgeRoute: typeof AppAiKnowledgeRoute
  AppAiLogsRoute: typeof AppAiLogsRoute
  AppAiIndexRoute: typeof AppAiIndexRoute
}

const AppAiRouteChildren: AppAiRouteChildren = {
  AppAiConfigRoute: AppAiConfigRoute,
  AppAiKnowledgeRoute: AppAiKnowledgeRoute,
  AppAiLogsRoute: AppAiLogsRoute,
  AppAiIndexRoute: AppAiIndexRoute,
}

const AppAiRouteWithChildren = AppAiRoute._addFileChildren(AppAiRouteChildren)

interface AppAppointmentsRouteChildren {
  AppAppointmentsIdRoute: typeof AppAppointmentsIdRoute
  AppAppointmentsNewRoute: typeof AppAppointmentsNewRoute
}

const AppAppointmentsRouteChildren: AppAppointmentsRouteChildren = {
  AppAppointmentsIdRoute: AppAppointmentsIdRoute,
  AppAppointmentsNewRoute: AppAppointmentsNewRoute,
}

const AppAppointmentsRouteWithChildren = AppAppointmentsRoute._addFileChildren(
  AppAppointmentsRouteChildren,
)

interface AppEmrRouteChildren {
  AppEmrIdRoute: typeof AppEmrIdRoute
  AppEmrRecordsRoute: typeof AppEmrRecordsRoute
  AppEmrTemplatesRoute: typeof AppEmrTemplatesRoute
  AppEmrIndexRoute: typeof AppEmrIndexRoute
  AppEmrConsentIdRoute: typeof AppEmrConsentIdRoute
  AppEmrConsentIndexRoute: typeof AppEmrConsentIndexRoute
}

const AppEmrRouteChildren: AppEmrRouteChildren = {
  AppEmrIdRoute: AppEmrIdRoute,
  AppEmrRecordsRoute: AppEmrRecordsRoute,
  AppEmrTemplatesRoute: AppEmrTemplatesRoute,
  AppEmrIndexRoute: AppEmrIndexRoute,
  AppEmrConsentIdRoute: AppEmrConsentIdRoute,
  AppEmrConsentIndexRoute: AppEmrConsentIndexRoute,
}

const AppEmrRouteWithChildren =
  AppEmrRoute._addFileChildren(AppEmrRouteChildren)

interface AppPatientsRouteChildren {
  AppPatientsIdRoute: typeof AppPatientsIdRoute
}

const AppPatientsRouteChildren: AppPatientsRouteChildren = {
  AppPatientsIdRoute: AppPatientsIdRoute,
}

const AppPatientsRouteWithChildren = AppPatientsRoute._addFileChildren(
  AppPatientsRouteChildren,
)

interface AppTherapistsRouteChildren {
  AppTherapistsIdRoute: typeof AppTherapistsIdRoute
}

const AppTherapistsRouteChildren: AppTherapistsRouteChildren = {
  AppTherapistsIdRoute: AppTherapistsIdRoute,
}

const AppTherapistsRouteWithChildren = AppTherapistsRoute._addFileChildren(
  AppTherapistsRouteChildren,
)

interface AppRouteChildren {
  AppAiRoute: typeof AppAiRouteWithChildren
  AppAppointmentsRoute: typeof AppAppointmentsRouteWithChildren
  AppBillingRoute: typeof AppBillingRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppEmrRoute: typeof AppEmrRouteWithChildren
  AppHomeVisitsRoute: typeof AppHomeVisitsRoute
  AppLocationsRoute: typeof AppLocationsRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppPatientsRoute: typeof AppPatientsRouteWithChildren
  AppProgrammesRoute: typeof AppProgrammesRoute
  AppProgressRoute: typeof AppProgressRoute
  AppServicesRoute: typeof AppServicesRoute
  AppTherapistsRoute: typeof AppTherapistsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiRoute: AppAiRouteWithChildren,
  AppAppointmentsRoute: AppAppointmentsRouteWithChildren,
  AppBillingRoute: AppBillingRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppEmrRoute: AppEmrRouteWithChildren,
  AppHomeVisitsRoute: AppHomeVisitsRoute,
  AppLocationsRoute: AppLocationsRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppPatientsRoute: AppPatientsRouteWithChildren,
  AppProgrammesRoute: AppProgrammesRoute,
  AppProgressRoute: AppProgressRoute,
  AppServicesRoute: AppServicesRoute,
  AppTherapistsRoute: AppTherapistsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
